//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public string Material { get; set; }
        public string Unit { get; set; }
        public string Category { get; set; }
        public int Discount { get; set; }
        public byte[] Photo { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Supplier { get; set; }

        
    }
}
